name: Deploy nginx to k3d

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Deploy to k3d cluster
        run: kubectl apply -f nginx-deployment.yaml

      - name: Deploy nginx service
        run: kubectl apply -f nginx-service.yaml

      - name: Print access URL
        run: echo "You can now reach the nginx page at [http://localhost:8080/](http://localhost:8080/)"
